WIP - CircleCI integration I

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,6 +20,7 @@ jobs:
           path:
             "bxextensions"
       - run: # install and activate virtual environment with pip
+          name: install virtual env
           command: |
             python -m virtualenv venv
             . venv/bin/activate
@@ -63,18 +64,18 @@ jobs:
           command: |
             cd ~/ws
             { # try
-                echo "Trying to clone identical branch name '$CIRCLE_BRANCH' from bxcommon."
-                git clone -b $CIRCLE_BRANCH --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon.git
-            } || { # catch
-                echo "Trying bxcommon develop branch, could not find identical branch name '$CIRCLE_BRANCH'."
-                git clone -b develop --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon.git
-            }
-            { # try
                 echo "Trying to clone identical branch name '$CIRCLE_BRANCH' from bxe2e."
                 git clone -b $CIRCLE_BRANCH --single-branch --depth=1 git@github.com:bloXroute-Labs/bxe2e.git
             } || { # catch
                 echo "Trying bxe2e develop branch, could not find identical branch name '$CIRCLE_BRANCH'."
                 git clone -b develop --single-branch --depth=1 git@github.com:bloXroute-Labs/bxe2e.git
+            }
+            { # try
+                echo "Trying to clone identical branch name '$CIRCLE_BRANCH' from bxcommon."
+                git clone -b $CIRCLE_BRANCH --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon.git
+            } || { # catch
+                echo "Trying bxcommon develop branch, could not find identical branch name '$CIRCLE_BRANCH'."
+                git clone -b develop --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon.git
             }
             { # try
                 echo "Trying to clone identical branch name '$CIRCLE_BRANCH' from bxrelay."
@@ -143,7 +144,7 @@ workflows:
             - initialize
       - e2e:
           requires:
-            - test
+            - initialize
       - build:
           requires:
             - test
